version: '3.7'
services:
  db:
    container_name: example_db
    image: postgres:9.5
    volumes:
      - example_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
      - POSTGRES_DB=example
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

volumes:
  example_db: {}